add 0.3.0 nodejs express repo config
using the latest 0.4 node.js express stack this sample gets the below exception on start. Maybe a problem with a newer level of Express. I updated the readme to use the 0.3.0 node.js stack so that app starts successfully.

```
[Container] [Thu Mar  5 16:04:46 2020] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
[Container] /project/server.js:35
[Container] app.use('/', userApp({
[Container]              ^
[Container] 
[Container] TypeError: userApp is not a function
[Container]     at Object.<anonymous> (/project/server.js:35:14)
[Container]     at Module._compile (internal/modules/cjs/loader.js:1158:30)
```